export { default as Home} from "./Home"
export { default as Shop} from "./Shop"
export { default as Cart} from "./Cart"
export { default as Tracking} from "./Tracking"
export { default as LogIn} from "./LogIn"
export { default as Payment} from "./Payment"
